version: "3.8"

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    image: laravel_react_app
    container_name: incident-backend
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=80"
    secrets:
      - db-password
    restart: always
    networks:
      - incident-net
    ports:
      - 8000:80
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.23
    container_name: incident-database
    command: --default-authentication-plugin=mysql_native_password
    secrets:
      - db-password
    networks:
      - incident-net
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db-mysql-incident:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=incident_app
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
volumes:
  db-mysql-incident:

secrets:
  db-password:
    file: password.txt
networks:
  incident-net:
